import os
import io
import sys
import PIL.Image as Image

# Ensure the script can import from bot/functions.py
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'bot'))
from bot import functions

OUTPUT_DIR = "mockups"
SCALE = 3.0  # Adjust this to change output fidelity (e.g., 2.0 = 2x resolution)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Monkey-patch Stamp.image to intercept the elements
original_stamp_image = functions.Stamp.image

CURRENT_PREFIX = "unknown"

def patched_stamp_image(self, chartPath, displayLegend=True, ticker=""):
    print(f"Intercepted Stamp.image for ticker: {ticker}")
    
    # 1. Save the raw chart generated by matplotlib
    chartPath.seek(0)
    chart_img = Image.open(chartPath).convert("RGBA")
    chart_img.save(os.path.join(OUTPUT_DIR, f"{CURRENT_PREFIX}_raw_chart.png"))
    
    # 2. Extract and save other elements if needed
    try:
        mainTemplate = Image.open("bot/assets/generation/template.png").convert("RGBA")
        mainTemplate.save(os.path.join(OUTPUT_DIR, f"{CURRENT_PREFIX}_background_template.png"))
        
        legendOverlay = Image.open("bot/assets/generation/legend.png").convert("RGBA")
        legendOverlay.save(os.path.join(OUTPUT_DIR, f"{CURRENT_PREFIX}_legend_overlay.png"))
        
        # Save icon if available
        if isinstance(self._serverIcon, str) and not self._serverIcon.startswith("http"):
            try:
                icon_img = Image.open(self._serverIcon).convert("RGBA")
                icon_img.save(os.path.join(OUTPUT_DIR, f"{CURRENT_PREFIX}_server_icon.png"))
            except Exception: pass
            
    except Exception as e:
        print(f"Error saving additional elements: {e}")

    # Generate the full final composite and save it as well
    chartPath.seek(0)
    final_buf = original_stamp_image(self, chartPath, displayLegend, ticker)
    if isinstance(final_buf, io.BytesIO):
        final_buf.seek(0)
        final_img = Image.open(final_buf)
        final_img.save(os.path.join(OUTPUT_DIR, f"{CURRENT_PREFIX}_final_composite.png"))
        final_buf.seek(0)
    
    return final_buf

functions.Stamp.image = patched_stamp_image

def patched_buffer(self, fig):
    fig.tight_layout()
    import matplotlib.collections as collections
    import matplotlib.lines as lines
    import matplotlib.text as text
    import matplotlib.patches as patches
    import matplotlib.axis as maxis
    import matplotlib.spines as mspines
    import matplotlib.image as image

    ax = fig.axes[0]
    
    def save_layer(name):
        buf = io.BytesIO()
        fig.savefig(buf, format="png", transparent=True, dpi=fig.dpi * SCALE)
        buf.seek(0)
        Image.open(buf).save(os.path.join(OUTPUT_DIR, f"{CURRENT_PREFIX}_{name}.png"))

    artists = ax.get_children()
    vis_states = {a: a.get_visible() for a in artists}

    def hide_data():
        for a in artists:
            if isinstance(a, (collections.PolyCollection, collections.PathCollection, lines.Line2D, patches.Patch, text.Text, text.Annotation, image.AxesImage)):
                if not isinstance(a, (mspines.Spine, maxis.XAxis, maxis.YAxis)):
                    a.set_visible(False)

    hide_data()
    fig.patch.set_alpha(0.0)
    ax.patch.set_alpha(0.0)
    save_layer("00_grid_and_axes")

    for a in artists:
        a.set_visible(False)
    ax.set_axis_off()
    
    grad_count = 0
    for i, a in enumerate(artists):
        if isinstance(a, image.AxesImage):
            a.set_visible(True)
            save_layer(f"05_gradient_{grad_count}")
            a.set_visible(False)
            grad_count += 1

    patch_count = 0
    for i, a in enumerate(artists):
        if isinstance(a, patches.Patch) and not isinstance(a, (mspines.Spine)):
            a.set_visible(True)
            save_layer(f"10_patch_{patch_count}")
            a.set_visible(False)
            patch_count += 1

    band_count = 0
    for i, a in enumerate(artists):
        if isinstance(a, collections.PolyCollection):
            a.set_visible(True)
            save_layer(f"20_forecast_band_{band_count}")
            a.set_visible(False)
            band_count += 1
            
    event_count = 0
    for i, a in enumerate(artists):
        if isinstance(a, collections.PathCollection):
            a.set_visible(True)
            save_layer(f"25_event_marker_{event_count}")
            a.set_visible(False)
            event_count += 1

    line_count = 0
    for i, a in enumerate(artists):
        if isinstance(a, lines.Line2D):
            a.set_visible(True)
            save_layer(f"30_line_{line_count}")
            a.set_visible(False)
            line_count += 1

    text_count = 0
    for i, a in enumerate(artists):
        if isinstance(a, (text.Text, text.Annotation)) and not isinstance(a, (maxis.XAxis, maxis.YAxis)):
            a.set_visible(True)
            save_layer(f"40_text_{text_count}")
            a.set_visible(False)
            text_count += 1

    for a, vis in vis_states.items():
        a.set_visible(vis)
    ax.set_axis_on()
    fig.patch.set_alpha(1.0)
    ax.patch.set_alpha(1.0)

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    import matplotlib.pyplot as plt
    plt.close(fig)
    buf.seek(0)
    return buf

functions.Charts._buffer = patched_buffer

def generate_mockups():
    global CURRENT_PREFIX
    print(f"Saving mockups to {OUTPUT_DIR}/...")
    charts = functions.Charts()
    functions.DB_LOCK = type("MockLock", (), {"__enter__": lambda s: None, "__exit__": lambda s, *a: None})()
    functions.recordRequest = lambda *args, **kwargs: None
    
    class MockCursor:
        def execute(self, *args, **kwargs): pass
        def fetchone(self): return None
        def fetchall(self): return []
        def __enter__(self): return self
        def __exit__(self, *args): pass
        
    class MockDB:
        def cursor(self): return MockCursor()
        def commit(self): pass
        
    functions.DB_CONNECTION = MockDB()

    test_tickers = ["NVDA"]
    
    for ticker in test_tickers:
        print(f"Processing history chart for {ticker}...")
        try:
            CURRENT_PREFIX = f"history_{ticker}"
            charts.history(ticker, "1mo", "1d", "Mock Server", "discord.gg/mock", "bot/assets/icons/discord.jpg", {}, None)
            
            print(f"Processing projection chart for {ticker}...")
            CURRENT_PREFIX = f"projection_{ticker}"
            charts.project(ticker, 2, "Mock Server", "discord.gg/mock", "bot/assets/icons/discord.jpg", None, "90d")
        except Exception as e:
            print(f"Error generating charts for {ticker}: {e}")

if __name__ == "__main__":
    generate_mockups()
    print("Done!")
